# Generated by Django 4.2.30 on 2026-05-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('content_preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='chatbot.chatmessage')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='chatbot_mes_message_d076f7_idx'), models.Index(fields=['document'], name='chatbot_mes_documen_1077e9_idx'), models.Index(fields=['chunk_id'], name='chatbot_mes_chunk_i_eb945e_idx')],
            },
        ),
    ]
