# Generated by Django 4.2.29 on 2026-05-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversationevaluation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationevaluation',
            new_name='chatbot_con_user_id_85ba48_idx',
            old_name='chatbot_con_user_id_51c9ce_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationevaluation',
            new_name='chatbot_con_rating_7a49c7_idx',
            old_name='chatbot_con_rating_8a66a1_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationevaluation',
            new_name='chatbot_con_is_pinn_5f2fc0_idx',
            old_name='chatbot_con_is_pinn_24fb0b_idx',
        ),
    ]
