# Generated by Django 4.2.29 on 2026-05-03 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('image', 'Image'), ('other', 'Other')], max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('indexed_chunks', models.PositiveIntegerField(default=0)),
                ('index_error', models.TextField(blank=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['project', '-uploaded_at'], name='documents_d_project_215c6e_idx'), models.Index(fields=['uploaded_by', '-uploaded_at'], name='documents_d_uploade_57d9b1_idx'), models.Index(fields=['index_status'], name='documents_d_index_s_63e36f_idx')],
            },
        ),
    ]
