# Generated by Django 4.2.29 on 2026-05-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_ocr_layout_extracted_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_chat_se_017659_idx',
            old_name='documents_d_chat_se_idx',
        ),
    ]
