# Generated by Django 4.2.29 on 2026-05-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0003_user_auth_token_version'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='twofactorloginchallenge',
            new_name='apps_auth_t_user_id_6f63e4_idx',
            old_name='apps_auth_t_user_id_64d2af_idx',
        ),
        migrations.RenameIndex(
            model_name='twofactorloginchallenge',
            new_name='apps_auth_t_expires_25d3fd_idx',
            old_name='apps_auth_t_expires_3db050_idx',
        ),
    ]
