# Generated by Django 4.2.29 on 2026-05-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatdocumentattachment',
            new_name='teams_chatd_chat_se_463d2a_idx',
            old_name='teams_chatd_chat_se_f03e94_idx',
        ),
        migrations.RenameIndex(
            model_name='chatdocumentattachment',
            new_name='teams_chatd_documen_a7628d_idx',
            old_name='teams_chatd_documen_c99af4_idx',
        ),
        migrations.RenameIndex(
            model_name='documentshare',
            new_name='teams_docum_shared__82e185_idx',
            old_name='teams_docum_shared_2a9c9b_idx',
        ),
        migrations.RenameIndex(
            model_name='documentshare',
            new_name='teams_docum_documen_9af70a_idx',
            old_name='teams_docum_documen_fdb779_idx',
        ),
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='teams_inapp_user_id_ce61f2_idx',
            old_name='teams_inapp_user_id_a8ee8f_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='teams_team_owner_i_5d4b82_idx',
            old_name='teams_team_owner_i_d9a21d_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='teams_team_name_43e047_idx',
            old_name='teams_team_name_f58822_idx',
        ),
        migrations.RenameIndex(
            model_name='teamdocument',
            new_name='teams_teamd_team_id_9f7d51_idx',
            old_name='teams_teamd_team_id_e7ab7e_idx',
        ),
        migrations.RenameIndex(
            model_name='teamdocument',
            new_name='teams_teamd_documen_dc701b_idx',
            old_name='teams_teamd_documen_af0d55_idx',
        ),
        migrations.RenameIndex(
            model_name='teaminvitation',
            new_name='teams_teami_email_74e450_idx',
            old_name='teams_teami_email_021155_idx',
        ),
        migrations.RenameIndex(
            model_name='teaminvitation',
            new_name='teams_teami_team_id_02e3eb_idx',
            old_name='teams_teami_team_id_f5f09d_idx',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='teams_teamm_team_id_4d95f6_idx',
            old_name='teams_teamm_team_id_58bb87_idx',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='teams_teamm_user_id_957e00_idx',
            old_name='teams_teamm_user_id_e86f41_idx',
        ),
    ]
